// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates reports that no updates are available via external channels,
 * as the application is packaged and updated through system package managers / Microsoft Store.
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(2783407158).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DownloadAndInstallUpdate is disabled since updates are managed externally by the system.
 */
export function DownloadAndInstallUpdate(downloadURL: string, assetName: string): $CancellablePromise<void> {
    return $Call.ByID(1630227666, downloadURL, assetName);
}

/**
 * GetCurrentVersion returns the hardcoded current application version
 */
export function GetCurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(67086334);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
