// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates queries the GitHub Releases API for the latest release
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(2783407158).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DownloadAndInstallUpdate downloads the binary and triggers installation
 */
export function DownloadAndInstallUpdate(downloadURL: string, assetName: string): $CancellablePromise<void> {
    return $Call.ByID(1630227666, downloadURL, assetName);
}

/**
 * GetCurrentVersion returns the hardcoded current application version
 */
export function GetCurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(67086334);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
