version: 2

project_name: Aura-Music

before:
  hooks:
    - go mod tidy

builds:
  - id: aura-linux
    binary: Aura-Music
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X changeme/internal/updater.CurrentVersion={{.Version}}
    dir: .

archives:
  - format: tar.gz
    name_template: "Aura-{{ .Os }}-{{ .Arch }}"

nfpms:
  - id: debian-packages
    package_name: aura-music
    file_name_template: "Aura-Linux-{{ .Arch }}"
    builds:
      - aura-linux
    formats:
      - deb
    vendor: Aura Inc
    homepage: https://github.com/AnilShebin/Aura-Player
    maintainer: Anil Shebin <anils@users.noreply.github.com>
    description: Lossless Music Player with TTML Karaoke support
    license: MIT
    section: sound
    priority: optional
    contents:
      - src: build/appicon.png
        dst: /usr/share/icons/hicolor/512x512/apps/aura-music.png
      - src: build/linux/desktop
        dst: /usr/share/applications/aura-music.desktop

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
