// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LyricsService provides lyrics fetching capabilities as a Wails-bound service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetLyrics extracts and parses lyrics for the given audio file path.
 * It returns a structured LyricsResult with synced timing, lines, and raw text.
 */
export function GetLyrics(filePath: string): $CancellablePromise<$models.LyricsResult> {
    return $Call.ByID(3985102649, filePath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetOnlineLyrics forces a lookup from LRCLIB, bypassing local sidecar/embedded files.
 * It returns a structured LyricsResult with synced timing, lines, and raw text.
 */
export function GetOnlineLyrics(filePath: string): $CancellablePromise<$models.LyricsResult> {
    return $Call.ByID(1481514762, filePath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PackLyrics embeds the lyrics text directly inside the audio file's metadata tags,
 * removing any legacy sidecar files (.lrc, .ttml, etc.) from the folder.
 * If direct embedding is not supported for the format, it falls back to saving a sidecar.
 */
export function PackLyrics(filePath: string, lyricsText: string, source: string): $CancellablePromise<$models.LyricsResult> {
    return $Call.ByID(1619569814, filePath, lyricsText, source).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveCustomLyrics caches the selected custom lyrics text and parses it to return to the UI.
 */
export function SaveCustomLyrics(filePath: string, lyricsText: string): $CancellablePromise<$models.LyricsResult> {
    return $Call.ByID(1059049617, filePath, lyricsText).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SearchOnlineLyrics queries LRCLIB for a search query and returns the matching results.
 */
export function SearchOnlineLyrics(query: string): $CancellablePromise<$models.LRCLibSearchResult[]> {
    return $Call.ByID(1029338320, query).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LyricsResult.createFrom;
const $$createType1 = $models.LRCLibSearchResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
