// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LyricsService provides lyrics fetching capabilities as a Wails-bound service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetLyrics extracts and parses lyrics for the given audio file path.
 * It returns a structured LyricsResult with synced timing, lines, and raw text.
 */
export function GetLyrics(filePath: string): $CancellablePromise<$models.LyricsResult> {
    return $Call.ByID(3985102649, filePath).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LyricsResult.createFrom;
