// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LRCLibSearchResult matches the track structure returned by LRCLIB search.
 */
export class LRCLibSearchResult {
    "id": number;
    "trackName": string;
    "artistName": string;
    "albumName": string;
    "duration": number;
    "plainLyrics": string;
    "syncedLyrics": string;

    /** Creates a new LRCLibSearchResult instance. */
    constructor($$source: Partial<LRCLibSearchResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("trackName" in $$source)) {
            this["trackName"] = "";
        }
        if (!("artistName" in $$source)) {
            this["artistName"] = "";
        }
        if (!("albumName" in $$source)) {
            this["albumName"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("plainLyrics" in $$source)) {
            this["plainLyrics"] = "";
        }
        if (!("syncedLyrics" in $$source)) {
            this["syncedLyrics"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LRCLibSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LRCLibSearchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LRCLibSearchResult($$parsedSource as Partial<LRCLibSearchResult>);
    }
}

/**
 * LyricLine represents a single parsed lyric line with timing.
 */
export class LyricLine {
    "time": number;
    "text": string;
    "is_translation": boolean;

    /** Creates a new LyricLine instance. */
    constructor($$source: Partial<LyricLine> = {}) {
        if (!("time" in $$source)) {
            this["time"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("is_translation" in $$source)) {
            this["is_translation"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LyricLine instance from a string or object.
     */
    static createFrom($$source: any = {}): LyricLine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LyricLine($$parsedSource as Partial<LyricLine>);
    }
}

/**
 * LyricsResult is the structured response returned to the frontend.
 */
export class LyricsResult {
    "synced": boolean;
    "lines": LyricLine[];
    "raw": string;
    "hasTTML": boolean;
    "source": string;

    /** Creates a new LyricsResult instance. */
    constructor($$source: Partial<LyricsResult> = {}) {
        if (!("synced" in $$source)) {
            this["synced"] = false;
        }
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }
        if (!("raw" in $$source)) {
            this["raw"] = "";
        }
        if (!("hasTTML" in $$source)) {
            this["hasTTML"] = false;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LyricsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LyricsResult {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField1_0($$parsedSource["lines"]);
        }
        return new LyricsResult($$parsedSource as Partial<LyricsResult>);
    }
}

// Private type creation functions
const $$createType0 = LyricLine.createFrom;
const $$createType1 = $Create.Array($$createType0);
