// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../database/sql/models.js";

export function AddFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(3341726428, path);
}

export function DeleteFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(1653168390, path);
}

export function GetDB(): $CancellablePromise<sql$0.DB | null> {
    return $Call.ByID(952839125).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetFolders(): $CancellablePromise<string[]> {
    return $Call.ByID(983653516).then(($result: any) => {
        return $$createType2($result);
    });
}

export function IsFirstTime(): $CancellablePromise<boolean> {
    return $Call.ByID(3016220900);
}

export function SetFirstTime(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(3618941146, value);
}

// Private type creation functions
const $$createType0 = sql$0.DB.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
