// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PlayerStatus {
    "filePath": string;
    "isPlaying": boolean;
    "currentTime": number;
    "duration": number;
    "volume": number;
    "ended": boolean;

    /** Creates a new PlayerStatus instance. */
    constructor($$source: Partial<PlayerStatus> = {}) {
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("isPlaying" in $$source)) {
            this["isPlaying"] = false;
        }
        if (!("currentTime" in $$source)) {
            this["currentTime"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("volume" in $$source)) {
            this["volume"] = 0;
        }
        if (!("ended" in $$source)) {
            this["ended"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayerStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PlayerStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayerStatus($$parsedSource as Partial<PlayerStatus>);
    }
}
