// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(1166855415);
}

export function GetStatus(): $CancellablePromise<$models.PlayerStatus> {
    return $Call.ByID(3388659533).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(3382574585);
}

export function Play(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(544745199, filePath);
}

export function Resume(): $CancellablePromise<void> {
    return $Call.ByID(346432798);
}

export function Seek(seconds: number): $CancellablePromise<void> {
    return $Call.ByID(966061285, seconds);
}

export function SetVolume(volume: number): $CancellablePromise<void> {
    return $Call.ByID(2979321353, volume);
}

// Private type creation functions
const $$createType0 = $models.PlayerStatus.createFrom;
